import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-debt-facility-interest-fee-audit",
  "engine": "recovery",
  "title": "Debt Facility Interest & Fee Audit",
  "shortTitle": "Debt Facility Interest and Fee Audit",
  "tagline": "Quantify, recover, and prevent financial leakage through debt facility interest & fee audit",
  "industry": "Corporate Debt Cost Recovery",
  "uiPort": 4635,
  "apiPort": 5635,
  "accent": "#be123c",
  "currency": "USD",
  "primaryOutcome": "Debt Facility Interest & Fee Audit converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect credit agreements, amendments, facilities, tranches, borrowings, repayments, base rates, spreads, floors, leverage grids, commitment fees, letters of credit, statements, and certificates in one accountable recovery workflow.",
  "calculation": {
    "actualKey": "chargedAmount",
    "expectedKey": "supportedAmount",
    "actualLabel": "Lender Charged Interest and Fees",
    "expectedLabel": "Agreement-Supported Cost",
    "varianceLabel": "Potential recovery or avoided cost",
    "direction": "actual-minus-expected",
    "finding": "Debt Facility Interest & Fee Audit evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective governing agreement and applicable rules",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare and submit the recovery or correction package",
      "Track counterparty response and reconcile realized outcome"
    ]
  }
},[
feature("credit-agreement-library","DFI01","Credit agreement library","Execute credit agreement library using credit agreements, amendments, facilities, tranches, borrowings, repayments, base rates, spreads, floors, leverage grids, commitment fees, letters of credit, statements, and certificates.","Produce a governed credit agreement library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Agent Bank / Debt Facility","text","Agent Bank / Debt Facility · Standard Case"],["caseReference","Credit agreement library Reference","text","DFI01-2026-001"],["chargedAmount","Lender Charged Interest and Fees","currency",1234000],["supportedAmount","Agreement-Supported Cost","currency",1061240],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["Credit agreement library case","Facility tranche registry case","Borrowing repayment ledger case","Base rate spread calculation case","Interest day-count validation case"]}),
feature("facility-tranche-registry","DFI02","Facility tranche registry","Execute facility tranche registry using credit agreements, amendments, facilities, tranches, borrowings, repayments, base rates, spreads, floors, leverage grids, commitment fees, letters of credit, statements, and certificates.","Produce a governed facility tranche registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Agent Bank / Debt Facility","text","Agent Bank / Debt Facility · Standard Case"],["caseReference","Facility tranche registry Reference","text","DFI02-2026-001"],["chargedAmount","Lender Charged Interest and Fees","currency",1234000],["supportedAmount","Agreement-Supported Cost","currency",1061240],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["Credit agreement library case","Facility tranche registry case","Borrowing repayment ledger case","Base rate spread calculation case","Interest day-count validation case"]}),
feature("borrowing-repayment-ledger","DFI03","Borrowing repayment ledger","Execute borrowing repayment ledger using credit agreements, amendments, facilities, tranches, borrowings, repayments, base rates, spreads, floors, leverage grids, commitment fees, letters of credit, statements, and certificates.","Produce a governed borrowing repayment ledger decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Agent Bank / Debt Facility","text","Agent Bank / Debt Facility · Standard Case"],["caseReference","Borrowing repayment ledger Reference","text","DFI03-2026-001"],["chargedAmount","Lender Charged Interest and Fees","currency",1234000],["supportedAmount","Agreement-Supported Cost","currency",1061240],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["Credit agreement library case","Facility tranche registry case","Borrowing repayment ledger case","Base rate spread calculation case","Interest day-count validation case"]}),
feature("base-rate-spread-calculation","DFI04","Base rate spread calculation","Execute base rate spread calculation using credit agreements, amendments, facilities, tranches, borrowings, repayments, base rates, spreads, floors, leverage grids, commitment fees, letters of credit, statements, and certificates.","Produce a governed base rate spread calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Agent Bank / Debt Facility","text","Agent Bank / Debt Facility · Standard Case"],["caseReference","Base rate spread calculation Reference","text","DFI04-2026-001"],["chargedAmount","Lender Charged Interest and Fees","currency",1234000],["supportedAmount","Agreement-Supported Cost","currency",1061240],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["Credit agreement library case","Facility tranche registry case","Borrowing repayment ledger case","Base rate spread calculation case","Interest day-count validation case"]}),
feature("interest-day-count-validation","DFI05","Interest day-count validation","Execute interest day-count validation using credit agreements, amendments, facilities, tranches, borrowings, repayments, base rates, spreads, floors, leverage grids, commitment fees, letters of credit, statements, and certificates.","Produce a governed interest day-count validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Agent Bank / Debt Facility","text","Agent Bank / Debt Facility · Standard Case"],["caseReference","Interest day-count validation Reference","text","DFI05-2026-001"],["chargedAmount","Lender Charged Interest and Fees","currency",1234000],["supportedAmount","Agreement-Supported Cost","currency",1061240],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["Credit agreement library case","Facility tranche registry case","Borrowing repayment ledger case","Base rate spread calculation case","Interest day-count validation case"]}),
feature("sofr-floor-fallback-control","DFI06","SOFR floor fallback control","Execute sofr floor fallback control using credit agreements, amendments, facilities, tranches, borrowings, repayments, base rates, spreads, floors, leverage grids, commitment fees, letters of credit, statements, and certificates.","Produce a governed sofr floor fallback control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Agent Bank / Debt Facility","text","Agent Bank / Debt Facility · Standard Case"],["caseReference","SOFR floor fallback control Reference","text","DFI06-2026-001"],["chargedAmount","Lender Charged Interest and Fees","currency",1234000],["supportedAmount","Agreement-Supported Cost","currency",1061240],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["Credit agreement library case","Facility tranche registry case","Borrowing repayment ledger case","Base rate spread calculation case","Interest day-count validation case"]}),
feature("leverage-grid-pricing","DFI07","Leverage grid pricing","Execute leverage grid pricing using credit agreements, amendments, facilities, tranches, borrowings, repayments, base rates, spreads, floors, leverage grids, commitment fees, letters of credit, statements, and certificates.","Produce a governed leverage grid pricing decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Agent Bank / Debt Facility","text","Agent Bank / Debt Facility · Standard Case"],["caseReference","Leverage grid pricing Reference","text","DFI07-2026-001"],["chargedAmount","Lender Charged Interest and Fees","currency",1234000],["supportedAmount","Agreement-Supported Cost","currency",1061240],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["Credit agreement library case","Facility tranche registry case","Borrowing repayment ledger case","Base rate spread calculation case","Interest day-count validation case"]}),
feature("unused-commitment-fee","DFI08","Unused commitment fee","Execute unused commitment fee using credit agreements, amendments, facilities, tranches, borrowings, repayments, base rates, spreads, floors, leverage grids, commitment fees, letters of credit, statements, and certificates.","Produce a governed unused commitment fee decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Agent Bank / Debt Facility","text","Agent Bank / Debt Facility · Standard Case"],["caseReference","Unused commitment fee Reference","text","DFI08-2026-001"],["chargedAmount","Lender Charged Interest and Fees","currency",1234000],["supportedAmount","Agreement-Supported Cost","currency",1061240],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["Credit agreement library case","Facility tranche registry case","Borrowing repayment ledger case","Base rate spread calculation case","Interest day-count validation case"]}),
feature("letter-of-credit-fee-audit","DFI09","Letter-of-credit fee audit","Execute letter-of-credit fee audit using credit agreements, amendments, facilities, tranches, borrowings, repayments, base rates, spreads, floors, leverage grids, commitment fees, letters of credit, statements, and certificates.","Produce a governed letter-of-credit fee audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Agent Bank / Debt Facility","text","Agent Bank / Debt Facility · Standard Case"],["caseReference","Letter-of-credit fee audit Reference","text","DFI09-2026-001"],["chargedAmount","Lender Charged Interest and Fees","currency",1234000],["supportedAmount","Agreement-Supported Cost","currency",1061240],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["Credit agreement library case","Facility tranche registry case","Borrowing repayment ledger case","Base rate spread calculation case","Interest day-count validation case"]}),
feature("default-interest-validation","DFI10","Default interest validation","Execute default interest validation using credit agreements, amendments, facilities, tranches, borrowings, repayments, base rates, spreads, floors, leverage grids, commitment fees, letters of credit, statements, and certificates.","Produce a governed default interest validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Agent Bank / Debt Facility","text","Agent Bank / Debt Facility · Standard Case"],["caseReference","Default interest validation Reference","text","DFI10-2026-001"],["chargedAmount","Lender Charged Interest and Fees","currency",1234000],["supportedAmount","Agreement-Supported Cost","currency",1061240],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["Credit agreement library case","Facility tranche registry case","Borrowing repayment ledger case","Base rate spread calculation case","Interest day-count validation case"]}),
feature("agent-lender-fee-reconciliation","DFI11","Agent lender fee reconciliation","Execute agent lender fee reconciliation using credit agreements, amendments, facilities, tranches, borrowings, repayments, base rates, spreads, floors, leverage grids, commitment fees, letters of credit, statements, and certificates.","Produce a governed agent lender fee reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Agent Bank / Debt Facility","text","Agent Bank / Debt Facility · Standard Case"],["caseReference","Agent lender fee reconciliation Reference","text","DFI11-2026-001"],["chargedAmount","Lender Charged Interest and Fees","currency",1234000],["supportedAmount","Agreement-Supported Cost","currency",1061240],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["Credit agreement library case","Facility tranche registry case","Borrowing repayment ledger case","Base rate spread calculation case","Interest day-count validation case"]}),
feature("compliance-certificate-linkage","DFI12","Compliance certificate linkage","Execute compliance certificate linkage using credit agreements, amendments, facilities, tranches, borrowings, repayments, base rates, spreads, floors, leverage grids, commitment fees, letters of credit, statements, and certificates.","Produce a governed compliance certificate linkage decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Agent Bank / Debt Facility","text","Agent Bank / Debt Facility · Standard Case"],["caseReference","Compliance certificate linkage Reference","text","DFI12-2026-001"],["chargedAmount","Lender Charged Interest and Fees","currency",1234000],["supportedAmount","Agreement-Supported Cost","currency",1061240],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["Credit agreement library case","Facility tranche registry case","Borrowing repayment ledger case","Base rate spread calculation case","Interest day-count validation case"]}),
feature("lender-statement-audit","DFI13","Lender statement audit","Execute lender statement audit using credit agreements, amendments, facilities, tranches, borrowings, repayments, base rates, spreads, floors, leverage grids, commitment fees, letters of credit, statements, and certificates.","Produce a governed lender statement audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Agent Bank / Debt Facility","text","Agent Bank / Debt Facility · Standard Case"],["caseReference","Lender statement audit Reference","text","DFI13-2026-001"],["chargedAmount","Lender Charged Interest and Fees","currency",1234000],["supportedAmount","Agreement-Supported Cost","currency",1061240],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["Credit agreement library case","Facility tranche registry case","Borrowing repayment ledger case","Base rate spread calculation case","Interest day-count validation case"]}),
feature("correction-workflow","DFI14","Correction workflow","Execute correction workflow using credit agreements, amendments, facilities, tranches, borrowings, repayments, base rates, spreads, floors, leverage grids, commitment fees, letters of credit, statements, and certificates.","Produce a governed correction workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Agent Bank / Debt Facility","text","Agent Bank / Debt Facility · Standard Case"],["caseReference","Correction workflow Reference","text","DFI14-2026-001"],["chargedAmount","Lender Charged Interest and Fees","currency",1234000],["supportedAmount","Agreement-Supported Cost","currency",1061240],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["Credit agreement library case","Facility tranche registry case","Borrowing repayment ledger case","Base rate spread calculation case","Interest day-count validation case"]}),
feature("facility-cost-analytics","DFI15","Facility cost analytics","Execute facility cost analytics using credit agreements, amendments, facilities, tranches, borrowings, repayments, base rates, spreads, floors, leverage grids, commitment fees, letters of credit, statements, and certificates.","Produce a governed facility cost analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Agent Bank / Debt Facility","text","Agent Bank / Debt Facility · Standard Case"],["caseReference","Facility cost analytics Reference","text","DFI15-2026-001"],["chargedAmount","Lender Charged Interest and Fees","currency",1234000],["supportedAmount","Agreement-Supported Cost","currency",1061240],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["Credit agreement library case","Facility tranche registry case","Borrowing repayment ledger case","Base rate spread calculation case","Interest day-count validation case"]})
]);
